# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following token is provided by GitHub Actions.
          # Do not expose it publicly.
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: aru6hi 
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Singapore
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_introduction: yes 
